# Generated by Django 4.1.5 on 2023-04-24 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("mysite", "0002_project_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("short_bio", models.TextField()),
                ("cv", models.FileField(upload_to="cv/")),
            ],
        ),
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("institution", models.CharField(max_length=100)),
                ("overview", models.TextField()),
                ("certificate", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("image", models.ImageField(upload_to="skills/")),
            ],
        ),
        migrations.CreateModel(
            name="SocialLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("link", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="WorkExperience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("company", models.CharField(max_length=100)),
                ("overview", models.TextField()),
                ("certificate", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "bio",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="mysite.bio"
                    ),
                ),
                ("contact", models.ManyToManyField(to="mysite.contact")),
                ("education", models.ManyToManyField(to="mysite.education")),
                ("projects", models.ManyToManyField(to="mysite.project")),
                ("skills", models.ManyToManyField(to="mysite.skill")),
                ("social_links", models.ManyToManyField(to="mysite.sociallink")),
                ("work_experience", models.ManyToManyField(to="mysite.workexperience")),
            ],
        ),
    ]
