# Generated by Django 4.1.5 on 2023-04-24 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("mysite", "0003_bio_education_skill_sociallink_workexperience_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutMe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("paragraph_top", models.TextField()),
                ("paragraph_bot", models.TextField()),
                ("cv", models.FileField(upload_to="cv/")),
            ],
        ),
        migrations.AlterField(
            model_name="profile",
            name="bio",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="mysite.aboutme"
            ),
        ),
        migrations.DeleteModel(
            name="Bio",
        ),
    ]
