# Generated by Django 4.1.5 on 2023-04-26 15:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mysite", "0004_aboutme_alter_profile_bio_delete_bio"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workexperience",
            name="certificate",
        ),
        migrations.AddField(
            model_name="education",
            name="year",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(1900),
                    django.core.validators.MaxValueValidator(9999),
                ],
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="workexperience",
            name="year",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(1900),
                    django.core.validators.MaxValueValidator(9999),
                ],
            ),
            preserve_default=False,
        ),
    ]
