# Generated by Django 4.1.5 on 2023-04-26 15:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mysite", "0005_remove_workexperience_certificate_education_year_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workexperience",
            name="year",
        ),
        migrations.AddField(
            model_name="workexperience",
            name="year_end",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(1990),
                    django.core.validators.MaxValueValidator(2023),
                ],
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="workexperience",
            name="year_start",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(1990),
                    django.core.validators.MaxValueValidator(2023),
                ],
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="education",
            name="year",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1990),
                    django.core.validators.MaxValueValidator(2023),
                ]
            ),
        ),
    ]
