# Generated by Django 4.1.5 on 2023-04-26 18:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mysite", "0006_remove_workexperience_year_workexperience_year_end_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PrimarySkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("image", models.ImageField(upload_to="static/primary_skills/")),
            ],
        ),
        migrations.CreateModel(
            name="SecondarySkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("image", models.ImageField(upload_to="static/secondary_skills/")),
            ],
        ),
        migrations.RemoveField(
            model_name="profile",
            name="skills",
        ),
        migrations.AlterField(
            model_name="aboutme",
            name="cv",
            field=models.FileField(upload_to="static/cv/"),
        ),
        migrations.DeleteModel(
            name="Skill",
        ),
        migrations.AddField(
            model_name="profile",
            name="primary_skills",
            field=models.ManyToManyField(to="mysite.primaryskill"),
        ),
        migrations.AddField(
            model_name="profile",
            name="secondary_skills",
            field=models.ManyToManyField(to="mysite.secondaryskill"),
        ),
    ]
