# Generated by Django 4.1.5 on 2023-04-26 18:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mysite", "0007_primaryskill_secondaryskill_remove_profile_skills_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="job_title",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="profile",
            name="nickname",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="profile",
            name="overview",
            field=models.TextField(blank=True, max_length=400),
        ),
    ]
