# Generated by Django 4.1.5 on 2023-04-26 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("mysite", "0008_profile_job_title_profile_nickname_profile_overview"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactMe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone_number", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                ("location", models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name="profile",
            name="contact",
        ),
        migrations.AddField(
            model_name="profile",
            name="contact",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="mysite.contactme",
            ),
        ),
    ]
