# Generated by Django 4.1.5 on 2023-06-27 15:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mysite", "0009_contactme_remove_profile_contact_profile_contact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="overview",
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
